### ISSUE TITLE
Flaming Eye Problems

### ISSUE THREAD

**Issue by OpenSauce55** [Night-Pryanik/No-Hope#3]
I recently got this  error while trying to run this mod, I'm pretty sure it has something to do with the flaming eye as it says it directly in the error. I made sure to see if it was other mods conflicting with it by running it by itself and still got this error. I tried downloading the release code and the source code and got the same error both ways. I put the installed folder in the data/mods folder so I'm not sure if I did anything wrong as I started playing this game like one or two weeks ago. Using Ellison-3 by the way. Well anyways, I hope you have a good day, cheers.

DEBUG    : Error: data/mods//No-Hope/enchantments.json: line 10:16: invalid flags: "NO_PROJECTILE"

    "effect": "bash",
    "extra_effects": [ { "id": "flaming_eye_damage" } ],
    "flags": [ "
               ^
                NO_PROJECTILE", "IGNORE_WALLS" ],
    "shape": "line",
    "min_damage": 999,

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 781

**Comment by Night-Pryanik** [comment]
Seems like the code to handle spells has changed. I'll look into this as soon as possible.

**Comment by Night-Pryanik** [comment]
Tested right now on latest experimental (0.E-9739) and no errors popped up.

I just reread your post and noticed you're trying to play the mod on Ellison-3. Could you please update to latest experimental and check if this error still shows up?

**Comment by OpenSauce55** [comment]
-Sorry for replying so late, had to do some stuff around the house.

Well I downloaded the latest experimental and the mod (Used the 2.7 version) does work. I was unaware that this mod was for the latest experimental releases and I was just playing the stable version. I was under the impression that most mods worked with the stable version or were made for the stable version. Didn't realize that the experimentals were waaaaaaaaaay ahead than the stable versions. Thought that most people played the stable version. On that note, what experimental version do you recommend? I have literally started only playing this game like 2 weeks ago, lol. 

Sorry for the trouble.

**Comment by Night-Pryanik** [comment]
No trouble at all.

I recommend playing the latest experimental. The latest stable is very old and contains lots of bugs that were fixed in experimentals. There were also new content, new features and improved performance in experimentals.
