### ISSUE TITLE
Forests generated in fields still have puddles of water in them

### ISSUE THREAD

**Issue by NetSysFire** [Night-Pryanik/No-Hope#4]
![image](https://user-images.githubusercontent.com/59517351/134503203-0fd680ce-0930-4832-81ec-10195e62e940.png)

These little groves are not marked as forests in the map but spawn randomly in fields. They still contain water. May be an overmap extra, just like the little meadow to the southeast and I do not know how it is called and how to find out its name, this is why I have the map editor open since it may provide necessary debug info.

Since these groves are relatively uncommon it may also be intended behavior, but I am not sure.

**Comment by Night-Pryanik** [comment]
Resolved by https://github.com/CleverRaven/Cataclysm-DDA/pull/53544.
